import { BarChart3, TrendingUp } from "lucide-react-native";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Card, SummaryCard } from "../components/ui";
import { useFinance } from "../data/FinanceContext";
import { useMembers } from "../data/MembersContext";
import { formatCurrency } from "../data/members";
import { colors, spacing, typography } from "../design";

const months = [{ label: "Mar", value: 72 }, { label: "Apr", value: 84 }, { label: "May", value: 78 }, { label: "Jun", value: 92 }, { label: "Jul", value: 61 }];
export function ReportsScreen() {
  const { members } = useMembers(); const { payments, expenses } = useFinance(); const income = payments.reduce((s, p) => s + p.amount, 0); const costs = expenses.reduce((s, e) => s + e.amount, 0); const rate = Math.round((members.filter((m) => m.status === "Paid").length / members.length) * 100);
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View><Text style={styles.title}>Performance</Text><Text style={styles.muted}>Collection and expense overview</Text></View>
    <View style={styles.grid}><SummaryCard label="Income" value={formatCurrency(income)} detail="All recorded" /><SummaryCard label="Net balance" value={formatCurrency(income - costs)} detail={`After ${formatCurrency(costs)} expenses`} accent="blue" /></View>
    <Card style={styles.chart}><View style={styles.head}><View><Text style={styles.section}>Collection trend</Text><Text style={styles.muted}>Last five months</Text></View><TrendingUp color={colors.status.paid} size={22} /></View><View style={styles.bars}>{months.map((month) => <View key={month.label} style={styles.barColumn}><View style={styles.barTrack}><View style={[styles.bar, { height: `${month.value}%` }]} /></View><Text style={styles.barLabel}>{month.label}</Text></View>)}</View></Card>
    <Card style={styles.metric}><BarChart3 color={colors.brand[600]} size={24} /><View style={styles.flex}><Text style={styles.section}>Collection rate</Text><Text style={styles.muted}>{members.filter((m) => m.status === "Paid").length} of {members.length} members paid</Text></View><Text style={styles.rate}>{rate}%</Text></Card>
    <Card style={styles.breakdown}><Text style={styles.section}>Status breakdown</Text><ReportRow label="Paid" value={members.filter((m) => m.status === "Paid").length} color={colors.status.paid} /><ReportRow label="Pending" value={members.filter((m) => m.status === "Pending").length} color={colors.status.pending} /><ReportRow label="Overdue" value={members.filter((m) => m.status === "Overdue").length} color={colors.status.unpaid} /></Card>
  </ScrollView>;
}
function ReportRow({ label, value, color }: { label: string; value: number; color: string }) { return <View style={styles.reportRow}><View style={[styles.dot, { backgroundColor: color }]} /><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.surface.app }, content: { padding: spacing[4], gap: spacing[4], paddingBottom: spacing[10] }, title: { ...typography.title, color: colors.ink[900] }, muted: { ...typography.caption, color: colors.ink[500] }, grid: { flexDirection: "row", gap: spacing[3], flexWrap: "wrap" }, chart: { gap: spacing[5] }, head: { flexDirection: "row", justifyContent: "space-between" }, section: { ...typography.sectionTitle, color: colors.ink[900] }, bars: { height: 150, flexDirection: "row", gap: spacing[3], alignItems: "flex-end" }, barColumn: { flex: 1, height: "100%", alignItems: "center", gap: spacing[2] }, barTrack: { flex: 1, width: "100%", justifyContent: "flex-end", backgroundColor: colors.surface.soft }, bar: { width: "100%", backgroundColor: colors.brand[600] }, barLabel: { ...typography.caption, color: colors.ink[500] }, metric: { flexDirection: "row", alignItems: "center", gap: spacing[3] }, flex: { flex: 1 }, rate: { fontSize: 24, fontWeight: "800", color: colors.brand[700] }, breakdown: { gap: spacing[4] }, reportRow: { flexDirection: "row", alignItems: "center", gap: spacing[3] }, dot: { width: 10, height: 10, borderRadius: 5 }, rowLabel: { ...typography.body, flex: 1, color: colors.ink[700] }, rowValue: { ...typography.label, color: colors.ink[900] } });
